#!/usr/bin/env @bash@/bin/bash
# Stolen from: https://github.com/Genki-S/dotfiles

COMMIT=$1

URL_BASE=`git config --get remote.origin.url | sed -e 's|git@|https://|' -e 's|:|/|g' -e 's|///|://|' -e 's|.git$||'`

URL=$URL_BASE

if [ -n "$COMMIT" ]; then
  URL="$URL/commit/$COMMIT"
fi

xdg-open $URL
