#!/usr/bin/env bash
target=$1
if [[ $(nmcli con show --active | grep tun0) ]]; then
    echo Active, deactivating
    nmcli con down VPN-${target}
else
    echo Not active, activating
    nmcli con up VPN-${target}
fi
